### ISSUE TITLE
Use of undeclared identifier 'MSACCustomProperties'

### ISSUE THREAD

**Issue by nibblesnbits** [microsoft/appcenter-sdk-react-native#955]
### **Description**

I cannot build my application after upgrading to 4.3.0

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install/configure via [these instructions](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native)
2. Build app
3. Observe these errors:
```
Use of undeclared identifier 'MSACCustomProperties' (at AppCenterReactNative.m:97)
Use of undeclared identifier 'customProperties' (7 times at AppCenterReactNative.m:107-121)
No known class method for selector 'setCustomProperties:' (at AppCenterReactNative.m:126)
```

### **Details**

1. Which version of the App Center SDK are you using? **4.3.0**
2. Which OS version did you experience the issue on? **iOS 15.2**
3. What device version did you see this error on?  Were you using an emulator or a physical device? **This occurs in the build phase**
4. What third party libraries are you using?
```
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-brands-svg-icons": "^5.15.3",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/react-native-fontawesome": "^0.2.6",
    "@hookform/resolvers": "^2.7.1",
    "@react-native-community/cli-platform-android": "^6.3.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-native-community/slider": "^4.1.12",
    "@react-native-firebase/app": "^14.2.4",
    "@react-native-firebase/dynamic-links": "^14.2.4",
    "@react-native-firebase/messaging": "^14.2.4",
    "@react-navigation/material-bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "accordion-collapse-react-native": "^1.0.1",
    "appcenter": "4.3.0",
    "appcenter-analytics": "4.3.0",
    "appcenter-crashes": "4.3.0",
    "babel": "^6.23.0",
    "babel-plugin-module-alias": "^1.6.0",
    "buffer": "^6.0.3",
    "humanize-plus": "^1.8.2",
    "intl": "^1.2.5",
    "lottie-react-native": "^4.0.3",
    "luxon": "^2.0.2",
    "mixpanel-react-native": "^1.3.5",
    "numeral": "^2.0.6",
    "react": "^17.0.2",
    "react-hook-form": "^7.22.4",
    "react-native": "^0.66.4",
    "react-native-actions-sheet": "^0.5.1",
    "react-native-config": "^1.4.4",
    "react-native-contacts": "^7.0.2",
    "react-native-date-picker": "^3.3.2",
    "react-native-device-info": "^8.3.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-keyboard-aware-view": "^0.0.14",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^2.1.5",
    "react-native-mmkv": "^2.0.0",
    "react-native-otp-textinput": "0.0.8",
    "react-native-paper": "^4.9.2",
    "react-native-progress": "^5.0.0",
    "react-native-push-notification": "^7.4.0",
    "react-native-radial-gradient": "^1.0.8",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.1",
    "react-native-securerandom": "^1.0.0",
    "react-native-sha256": "^1.4.7",
    "react-native-sound-player": "^0.11.1",
    "react-native-svg": "^12.1.1",
    "react-native-toast-message": "^1.6.0",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-vector-icons": "^8.1.0",
    "react-native-web-swiper": "^2.2.1",
    "react-relay": "^13.0.1",
    "relay-runtime": "^13.0.1",
    "sha.js": "^2.4.11",
    "subscriptions-transport-ws": "^0.9.19",
    "url": "^0.11.0",
    "use-http": "^1.0.26",
    "yup": "^0.32.9"
  }

```

5. Run the following command and paste the output below: `react-native info`
```
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 182.17 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 8.3.1 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

```
1.11.2
```

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:
** I can't build **

### Other Notes
I've already tried cleaning my build folder, uninstalling/reinstalling packages, and deleting `Pods/` and `Podfile.lock` and reinstalling the pods.

**Comment by nibblesnbits** [comment]
My appcenter entries in my `Podfile.lock` are:

```
  - appcenter-analytics (4.3.0):
    - AppCenter/Analytics (~> 4.0)
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - appcenter-core (4.3.0):
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - appcenter-crashes (4.3.0):
    - AppCenter/Crashes (~> 4.0)
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - AppCenter/Analytics (4.4.1):
    - AppCenter/Core
  - AppCenter/Core (4.4.1)
  - AppCenter/Crashes (4.4.1):
    - AppCenter/Core
  - AppCenterReactNativeShared (4.4.3):
    - AppCenter/Core (= 4.4.1)
```

**Comment by gordon-eliel** [comment]
Having the same issue, downgrading doesn't seem to solve it. Using ReactNative v0.66.4

**Comment by thegdznet** [comment]
HI!

Same problem here...

**Comment by vretamal** [comment]
Hi! Same problem here, same versions

**Comment by thegdznet** [comment]
Hi! As a temporary workaround, downgrading to v3.1.3 works fine.

**Comment by jaraujocds** [comment]
Same problem here!

**Comment by gordon-eliel** [comment]
Downgrading alone did not work for me. I looked into the Podfile generated by appcenter, and found that MSACAppCenter was not included in the source. I was importing #import <AppCenter/MSACAppCenter.h> and using [MSAppCenter configureWithAppSecret: appCenterSecret]; to configure app center at runtime. 

Solution for downgrading to v3.1.3 from c4.3.0:
1. Use #import <AppCenter/MSAppCenter.h> **instead** of  #import <AppCenter/MSACAppCenter.h>
2. Use MSAppCenter instead of MSACAppCenter

**Comment by AnatolyPristensky** [comment]
Hello all,
Sorry for inconvenience, It's a known issue and it has been fixed with a new version 4.4.3. 
Could you please try to update on a latest version and check if the issue is gone.

**Comment by thegdznet** [comment]
Hi.

Just tried v4.4.3. Error is still there.

yarn.lock:

```
appcenter-analytics@4.4.3:
  version "4.4.3"
  resolved "https://registry.yarnpkg.com/appcenter-analytics/-/appcenter-analytics-4.4.3.tgz#a49d8e50fed6df6de8b06a8a9a9e54adf35df54c"
  integrity sha512-fcVuxl/swf5LMmt95AlDdP2gMyvHTUGZODrl1FFpWYo8Np5mWBvTEQr0mEIOilDToCa4NljQHID+3PeBK+Asqg==
  dependencies:
    appcenter "4.4.3"

appcenter-crashes@4.4.3:
  version "4.4.3"
  resolved "https://registry.yarnpkg.com/appcenter-crashes/-/appcenter-crashes-4.4.3.tgz#f5f7e0dfbae4a19ae5560575fe1a5b77a3d9b5a6"
  integrity sha512-vroN9XvsEzkVXsidO9F0h+lALR5+YIVrt2TqbeTTAUHEQBemJMp3V1wudw/3xPKRm7D+UaOrEf1t0xoQZi52SA==
  dependencies:
    appcenter "4.4.3"

appcenter-link-scripts@4.4.3:
  version "4.4.3"
  resolved "https://registry.yarnpkg.com/appcenter-link-scripts/-/appcenter-link-scripts-4.4.3.tgz#e0c32693da94954756f5202fca899aa02db90cd8"
  integrity sha512-9rp4bqni8SxyFHdYCesWZaHDl2eK07DdKPXABsTHIo0a07yq2eo99FlkSxEHpu3TQNwjnTQRObQ+FtlABYcveQ==
  dependencies:
    debug "4.1.1"
    glob "5.0.15"
    minimist "1.2.5"
    mkdirp "0.5.3"
    plist "^3.0.2"
    which "1.2.11"
    xcode "2.0.0"

appcenter@4.4.3:
  version "4.4.3"
  resolved "https://registry.yarnpkg.com/appcenter/-/appcenter-4.4.3.tgz#834c77faf4cc6e8b69d712a7edb081e0312f370a"
  integrity sha512-4AnVZnjh0oJvnW466Tk8DK7Fn0ZkMYC4G5aJn7j3yKc2kWAfnNHAOF8V9BAGpIOAZCTyEQy8Wx3iCqrR0rSBEg==
  dependencies:
    appcenter-link-scripts "4.4.3"
```

Podile.lock

```
  - appcenter-analytics (4.4.3):
    - AppCenter/Analytics (~> 4.0)
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - appcenter-core (4.4.3):
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - appcenter-crashes (4.4.3):
    - AppCenter/Crashes (~> 4.0)
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - AppCenter/Analytics (4.4.1):
    - AppCenter/Core
  - AppCenter/Core (4.4.1)
  - AppCenter/Crashes (4.4.1):
    - AppCenter/Core
  - AppCenterReactNativeShared (4.4.3):
    - AppCenter/Core (= 4.4.1)
```

I have completely cleaned node_modules and Xcode DerivedData folders.

**Comment by thegdznet** [comment]
Hi again. As I don't use setCustomProperties, for now, I will comment the body and create a patch.

**Comment by Thunderbird7** [comment]
I trying upgrade sdk to v4.4.3, works fine. 👏

**Comment by thegdznet** [comment]
Hi. Running fine with v4.4.3. Thanx++ for Your help and quick answer.

**Comment by aaronrondina5** [comment]
4.3.3 worked for me as well

**Comment by duynghiale** [comment]
I also upgraded version 4.4.3 but still build error

**Comment by DmitriyKirakosyan** [comment]
Hi @duynghiale, we recommend using the latest version (currently 5.0.2). Please update to this version. If the issue persists, kindly share your build error log.
