### ISSUE TITLE
fatal error: 'React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by davidpricedev** [Microsoft/AppCenter-SDK-React-Native#368]
### **Description**

I'm seeing issues with what looks like header path issues in the latest version. Specifically:

> In file included from /Users/me/dev/myapp/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:11:
/Users/me/dev/myapp/node_modules/react-native/React/Base/RCTAssert.h:10:9: fatal error: 'React/RCTDefines.h' file not found
> #import <React/RCTDefines.h>
>               ^~~~~~~~~~~~~~~~~~~~

### **Repro Steps**

* Start with a working build with react-native@0.56.0 and appcenter-*@1.3.0 (there are runtime issues with this configuration due to the appcenter/react-native mismatch, but the build works)
* Upgrade appcenter components to 1.6.0 or 1.7.1

### **Details**

1. Which SDK version are you using?
    * 1.7.1
2. Which OS version did you experience the issue on?
    * iOS 11
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    * either emulator via `react-native run-ios` or a physical device via xcode
4. What third party libraries are you using?
    * a few: appcenter-{crashes,push,analytics}, code-push, react-native-fcm, react-native-camera, react-native-maps are some of the big ones.
5. Run the following command and paste the output below: `react-native info`
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 2.38 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 5.5.1 - ~/.nvm/versions/node/v8.9.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.0
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```
6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`
    * `1.5.3`

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:
    * N/A - this is a build issue so runtime logs won't be useful. 

### **What I've already tried**

I had a look though [this SO](https://stackoverflow.com/questions/12002905/ios-build-fails-with-cocoapods-cannot-find-header-files), [this comment](https://github.com/facebook/react-native/issues/11813#issuecomment-273279257), and [this issue](https://github.com/facebook/react-native/issues/12265) and tried all the suggestions there to no avail.

I've also done this a few times, followed by trying to build in xcode:
`rm -rf node_modules; rm -rf ~/Library/Developer/Xcode/DerivedData; rm -rf ios; git reset --hard; yarn install; cd ios; pod install; cd ..;`

**Comment by jaelim-ms** [comment]
Have you followed update steps described in the [doc](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native#how-to-update-react-native-sdk-to-the-latest-version)?
I tried to reproduce your issue by starting with 1.3.0 and then update to 1.7.1 but no luck. 1.6.0 wouldn't work with RN 0.56.0 but 1.7.1 should just work. Please uninstall AppCenter SDK from your application and install again followed by `react-native link`.

**Comment by davidpricedev** [comment]
I hadn't used those exact steps, but something very similar. I just ran through that and I don't see any new changes on the ios side. I'm seeing the same error message too.

My colleage tried this on their system and they get a different result with the same code, though still a failing build.
> ld: 18 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ld: warning: directory not found for option '-L/Users/me/Library/Developer/Xcode/DerivedData/myapp-boeucywrqmrxzadiblgxuhydsbtx/Build/Products/Debug-iphonesimulator/React'

**Comment by davidpricedev** [comment]
I did depart from the documented upgrade steps there in one regard - I have an entry in the podfile for AppCenterReactNativeShared: 
`pod 'AppCenterReactNativeShared', '~> 1.7.1'` 
which I had to manually update to 1.7.1 from 1.3.0.

**Comment by jaelim-ms** [comment]
@davidpricedev Once you run `react-native link` after uninstall/install to the latest version, link script will automatically update the version in Podfile. It doesn't require manual steps to update the version.
Can you give me more details on the build issue that your colleague had? I feel like this is Xcode cache issue. Simply clean the project and remove `/Users/me/Library/Developer/Xcode/DerivedData/myapp-boeucywrqmrxzadiblgxuhydsbtx` folder and then rebuild could fix the issue.

**Comment by davidpricedev** [comment]
I think I was able to resolve this. I ripped out all the appcenter components and got xcode to build and then followed the current initial install steps. I ended up with very different content in my Podfile and AppDelegate.m file.

Podfile changes
- `pod 'AppCenterReactNativeShared', '~> 1.0.1'` removed
-  All the other appcenter podfile entries got switched from path references to version references.

AppDelegate.m changes
- `@import AppCenter;` removed
- `[AppCenterReactNative register];  // Initialize AppCenter` removed

The AppcenterConfig.plist file wasn't linked in with the install steps and without it things weren't working, so I added that back manually in xcode.
